### PR TITLE
file opening: use path str instead of file object

### PR DESCRIPTION
**Pull request by chongxiaoc**
open() is not working for hdfs path

### CODE REVIEW

**Comment by chongxiaoc** [comment]
@clarkzinzow FYI

**Comment by clarkzinzow** [comment]
@chongxiaoc That's surprising that HDFS isn't currently working, we're using `open` from [`smart-open`](https://pypi.org/project/smart-open/) there in order to support efficient reading and writing to a bunch of different storage backends (local filesystem, S3, GCS, HDFS, etc.), and HDFS URIs should work out-of-the-box. 🤔 

If `smart-open` isn't working as expected, maybe we should move to something like [`fsspec`](https://filesystem-spec.readthedocs.io/en/latest/index.html), since I don't think that the Pandas IO engines for Parquet files will correctly handle all storage backends.

**Comment by clarkzinzow** [comment]
It actually looks like recent Pandas has native `fsspec` support, so if `fsspec` is installed and an `fsspec`-type URI is provided, it should transparently use `fsspec` + the specified Parquet engine when reading/writing Parquet files. So maybe removing the `smart-open` dependency and the `open()` wrapper, and adding `fsspec` as a dependency is the way to go.

**Comment by chongxiaoc** [comment]
Yep, I saw `smart_open` is being called, but it is kind of mysterious on our cluster that it complains `path doesn't exist` in `open()`, since it is a write operation for a new file.

**Comment by clarkzinzow** [comment]
Very strange indeed. Would you mind if I pushed a commit to this branch that removes `smart-open` and the `open()` calls, and adds `fsspec` as a dependency (and whatever else is required to let Pandas handle raw file URIs correctly)?

**Comment by chongxiaoc** [comment]
Verified again, `smart_open` is not working with hdfs path on uber cluster.

**Review by rkooo567 — APPROVED** [review]

**Comment by clarkzinzow** [comment]
@chongxiaoc I removed `smart-open`, added `fsspec` as a dependency, and ported the stats file writing to `fsspec`. This looks good to merge!

**Pull request merged**
